/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CipherSshKeyModel {
    #[serde(rename = "privateKey", skip_serializing_if = "Option::is_none")]
    pub private_key: Option<String>,
    #[serde(rename = "publicKey", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<String>,
    #[serde(rename = "keyFingerprint", skip_serializing_if = "Option::is_none")]
    pub key_fingerprint: Option<String>,
}

impl CipherSshKeyModel {
    pub fn new() -> CipherSshKeyModel {
        CipherSshKeyModel {
            private_key: None,
            public_key: None,
            key_fingerprint: None,
        }
    }
}
