/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

/// MemberAccessReportResponseModel : Contains the collections and group collections a user has
/// access to including  the permission level for the collection and group collection.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemberAccessReportResponseModel {
    #[serde(rename = "userName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "twoFactorEnabled", skip_serializing_if = "Option::is_none")]
    pub two_factor_enabled: Option<bool>,
    #[serde(
        rename = "accountRecoveryEnabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_recovery_enabled: Option<bool>,
    #[serde(rename = "groupsCount", skip_serializing_if = "Option::is_none")]
    pub groups_count: Option<i32>,
    #[serde(rename = "collectionsCount", skip_serializing_if = "Option::is_none")]
    pub collections_count: Option<i32>,
    #[serde(rename = "totalItemCount", skip_serializing_if = "Option::is_none")]
    pub total_item_count: Option<i32>,
    #[serde(rename = "userGuid", skip_serializing_if = "Option::is_none")]
    pub user_guid: Option<uuid::Uuid>,
    #[serde(rename = "usesKeyConnector", skip_serializing_if = "Option::is_none")]
    pub uses_key_connector: Option<bool>,
    #[serde(rename = "accessDetails", skip_serializing_if = "Option::is_none")]
    pub access_details: Option<Vec<models::MemberAccessDetails>>,
}

impl MemberAccessReportResponseModel {
    /// Contains the collections and group collections a user has access to including  the
    /// permission level for the collection and group collection.
    pub fn new() -> MemberAccessReportResponseModel {
        MemberAccessReportResponseModel {
            user_name: None,
            email: None,
            two_factor_enabled: None,
            account_recovery_enabled: None,
            groups_count: None,
            collections_count: None,
            total_item_count: None,
            user_guid: None,
            uses_key_connector: None,
            access_details: None,
        }
    }
}
