/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationCollectionManagementUpdateRequestModel {
    #[serde(
        rename = "limitCollectionCreation",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit_collection_creation: Option<bool>,
    #[serde(
        rename = "limitCollectionDeletion",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit_collection_deletion: Option<bool>,
    #[serde(
        rename = "allowAdminAccessToAllCollectionItems",
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_admin_access_to_all_collection_items: Option<bool>,
}

impl OrganizationCollectionManagementUpdateRequestModel {
    pub fn new() -> OrganizationCollectionManagementUpdateRequestModel {
        OrganizationCollectionManagementUpdateRequestModel {
            limit_collection_creation: None,
            limit_collection_deletion: None,
            allow_admin_access_to_all_collection_items: None,
        }
    }
}
