/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreValidateSponsorshipResponseModel {
    #[serde(rename = "isTokenValid", skip_serializing_if = "Option::is_none")]
    pub is_token_valid: Option<bool>,
    #[serde(
        rename = "isFreeFamilyPolicyEnabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_free_family_policy_enabled: Option<bool>,
}

impl PreValidateSponsorshipResponseModel {
    pub fn new() -> PreValidateSponsorshipResponseModel {
        PreValidateSponsorshipResponseModel {
            is_token_valid: None,
            is_free_family_policy_enabled: None,
        }
    }
}
