/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerSettingsResponseModel {
    #[serde(
        rename = "disableUserRegistration",
        skip_serializing_if = "Option::is_none"
    )]
    pub disable_user_registration: Option<bool>,
}

impl ServerSettingsResponseModel {
    pub fn new() -> ServerSettingsResponseModel {
        ServerSettingsResponseModel {
            disable_user_registration: None,
        }
    }
}
