/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenizedPaymentSourceRequestBody {
    #[serde(rename = "type")]
    pub r#type: models::PaymentMethodType,
    #[serde(rename = "token")]
    pub token: String,
}

impl TokenizedPaymentSourceRequestBody {
    pub fn new(
        r#type: models::PaymentMethodType,
        token: String,
    ) -> TokenizedPaymentSourceRequestBody {
        TokenizedPaymentSourceRequestBody { r#type, token }
    }
}
