/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePaymentMethodRequestBody {
    #[serde(rename = "paymentSource")]
    pub payment_source: Box<models::TokenizedPaymentSourceRequestBody>,
    #[serde(rename = "taxInformation")]
    pub tax_information: Box<models::TaxInformationRequestBody>,
}

impl UpdatePaymentMethodRequestBody {
    pub fn new(
        payment_source: models::TokenizedPaymentSourceRequestBody,
        tax_information: models::TaxInformationRequestBody,
    ) -> UpdatePaymentMethodRequestBody {
        UpdatePaymentMethodRequestBody {
            payment_source: Box::new(payment_source),
            tax_information: Box::new(tax_information),
        }
    }
}
