/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifiedOrganizationDomainSsoDetailResponseModel {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(rename = "domainName", skip_serializing_if = "Option::is_none")]
    pub domain_name: Option<String>,
    #[serde(
        rename = "organizationIdentifier",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_identifier: Option<String>,
    #[serde(rename = "organizationName", skip_serializing_if = "Option::is_none")]
    pub organization_name: Option<String>,
}

impl VerifiedOrganizationDomainSsoDetailResponseModel {
    pub fn new() -> VerifiedOrganizationDomainSsoDetailResponseModel {
        VerifiedOrganizationDomainSsoDetailResponseModel {
            object: None,
            domain_name: None,
            organization_identifier: None,
            organization_name: None,
        }
    }
}
