name: Check Rust feature-powerset

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Building for ${{ matrix.os }}

    runs-on: ${{ matrix.os || 'ubuntu-24.04' }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-24.04
          - windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install rust
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # stable
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7

      - name: Install cargo-hack
        run: cargo install cargo-hack --version 0.6.33 --locked

      - name: Build
        run: cargo hack check --workspace --feature-powerset --no-dev-deps
        env:
          RUSTFLAGS: "-D warnings"
