name: Direct Minimum Version

on:
  pull_request:
  push:
    branches:
      - "main"
      - "rc"
      - "hotfix-rc"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  direct-minimal-versions:
    name: Check dependencies minimal versions for - ${{ matrix.settings.os }} - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.os || 'ubuntu-24.04' }}
    env:
      RUST_NIGHTLY_TOOLCHAIN: nightly-2025-01-13

    strategy:
      fail-fast: false
      matrix:
        settings:
          #- os: macos-14
          #  target: x86_64-apple-darwin

          #- os: macos-14
          #  target: aarch64-apple-darwin

          - os: windows-2022
            target: x86_64-pc-windows-msvc

          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install rust
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # stable
        with:
          toolchain: "$RUST_NIGHTLY_TOOLCHAIN"
          targets: ${{ matrix.settings.target }}

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
        with:
          key: dmv-${{ matrix.settings.target }}-cargo-${{ matrix.settings.os }}

      - name: Cargo check direct-minimal-versions
        run: cargo check -Z direct-minimal-versions --all-features
