name: Test for memory leaks

on:
  pull_request:
    paths:
      - "crates/bitwarden-crypto/**"
      - "crates/memory-testing/**"
  push:
    paths:
      - "crates/bitwarden-crypto/**"
      - "crates/memory-testing/**"
    branches:
      - "main"
      - "rc"
      - "hotfix-rc"

jobs:
  memory-test:
    name: Testing
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up gdb
        run: |
          sudo apt update
          sudo apt -y install gdb

      - name: Install rust
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # stable
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
        with:
          key: memtest-cargo

      - name: Test
        run: ./crates/memory-testing/run_test.sh no-docker
